// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DSTPrototypeCore","status":true,"description":"Survival/action prototype systems: pseudo-2.5D support, outline, debug panel, HUD inventory, held items, simple combat","parameters":{}}
];
